[[command]]
name = "script"
module = "wasmer/winterjs:winterjs"
runner = "wasi"

[command.annotations.wasi]
main-args = [ "--mode", "cloudflare", "/web",]

[package]
name = "theduke/nextjs-test-12345"
version = "0.3.1"
description = "Next.js Server Componenents starter package"
readme = "README.md"
repository = "https://github.com/theduke/nextjs-test-12345"

[dependencies]
"wasmer/winterjs" = "^0.4.4"

[fs]
"/web" = ".vercel/output/static"
